### ISSUE TITLE
Error with the kucoin sdk

### ISSUE THREAD

**Issue by skrew** [arya-araban/kucoin-buyer#1]
Hi,

`pip3 install kucoin-python`

```
python3 pump-discord.py

Traceback (most recent call last):
  File "pump-discord.py", line 5, in <module>
    import config
  File "/home/coins/utils/kucoin-buyer/config.py", line 1, in <module>
    from kucoin.client import Client
ImportError: cannot import name 'Client' from 'kucoin.client' (/usr/local/lib/python3.8/dist-packages/kucoin/client.py)
```

**Comment by skrew** [comment]
Ok it's `python-kucoin` and not `kucoin-python`
